# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal C++ implementation of the Prize-Collecting Steiner Forest algorithm
#'
#' Adapted from PCSF by Murodzhon Akhmedov et al. (MIT License, 2017).
#' https://github.com/IOR-Bioinformatics/PCSF
#'
#' @keywords internal
#'
#' @param from  A \code{CharacterVector} of head nodes.
#' @param to A \code{CharacterVector} of tail nodes.
#' @param cost A \code{NumericVector} of edge weights.
#' @param node_names A \code{CharacterVector} of node names.
#' @param node_prizes A \code{NumericVector} of node prizes.
#'
call_sr <- function(from, to, cost, node_names, node_prizes) {
    .Call('_iPCSF_call_sr', PACKAGE = 'iPCSF', from, to, cost, node_names, node_prizes)
}

